
LOCATIONS_DATA = [
    # Philippines (Primary focus)
    'Manila, Philippines',
    'Cebu, Philippines',
    'Davao, Philippines',
    'Quezon City, Philippines',
    'Makati, Philippines',
    'Pasig, Philippines',
    'Taguig, Philippines',
    'Antipolo, Philippines',
    'Pasay, Philippines',
    'Cagayan de Oro, Philippines',
    'Iloilo, Philippines',
    'Bacolod, Philippines',
    'Baguio, Philippines',
    'Zamboanga, Philippines',
    'Caloocan, Philippines',
    'Marikina, Philippines',
    'Parañaque, Philippines',
    'Las Piñas, Philippines',
    'Muntinlupa, Philippines',
    'San Juan, Philippines',
    'Mandaluyong, Philippines',
    'Malabon, Philippines',
    'Navotas, Philippines',
    'Valenzuela, Philippines',
    'Pateros, Philippines',
    'Lapu-Lapu, Philippines',
    'Mandaue, Philippines',
    'Talisay, Philippines',
    'Bohol, Philippines',
    'Dumaguete, Philippines',
    
    # United States
    'New York, United States',
    'Los Angeles, United States',
    'Chicago, United States',
    'Houston, United States',
    'Phoenix, United States',
    'Philadelphia, United States',
    'San Antonio, United States',
    'San Diego, United States',
    'Dallas, United States',
    'San Jose, United States',
    'Austin, United States',
    'Jacksonville, United States',
    'Fort Worth, United States',
    'Columbus, United States',
    'Charlotte, United States',
    'San Francisco, United States',
    'Indianapolis, United States',
    'Seattle, United States',
    'Denver, United States',
    'Washington, United States',
    'Boston, United States',
    'Nashville, United States',
    'Baltimore, United States',
    'Louisville, United States',
    'Portland, United States',
    'Oklahoma City, United States',
    'Milwaukee, United States',
    'Las Vegas, United States',
    'Albuquerque, United States',
    'Tucson, United States',
    'Fresno, United States',
    'Sacramento, United States',
    'Kansas City, United States',
    'Mesa, United States',
    'Atlanta, United States',
    'Colorado Springs, United States',
    'Raleigh, United States',
    'Omaha, United States',
    'Miami, United States',
    'Oakland, United States',
    'Minneapolis, United States',
    'Tulsa, United States',
    'Cleveland, United States',
    'Wichita, United States',
    'Arlington, United States',
    'Tampa, United States',
    'Bakersfield, United States',
    'New Orleans, United States',
    'Honolulu, United States',
    'Anaheim, United States',
    'Santa Ana, United States',
    'Corpus Christi, United States',
    'Riverside, United States',
    'Lexington, United States',
    'St. Louis, United States',
    'Stockton, United States',
    'Pittsburgh, United States',
    'St. Paul, United States',
    'Cincinnati, United States',
    'Anchorage, United States',
    'Henderson, United States',
    'Greensboro, United States',
    'Plano, United States',
    'Newark, United States',
    'Lincoln, United States',
    'Toledo, United States',
    'Orlando, United States',
    
    # United Kingdom
    'London, United Kingdom',
    'Birmingham, United Kingdom',
    'Manchester, United Kingdom',
    'Glasgow, United Kingdom',
    'Liverpool, United Kingdom',
    'Leeds, United Kingdom',
    'Sheffield, United Kingdom',
    'Edinburgh, United Kingdom',
    'Bristol, United Kingdom',
    'Cardiff, United Kingdom',
    'Leicester, United Kingdom',
    'Coventry, United Kingdom',
    'Bradford, United Kingdom',
    'Nottingham, United Kingdom',
    'Kingston upon Hull, United Kingdom',
    'Newcastle upon Tyne, United Kingdom',
    'Belfast, United Kingdom',
    'Stoke-on-Trent, United Kingdom',
    'Southampton, United Kingdom',
    'Derby, United Kingdom',
    'Portsmouth, United Kingdom',
    'Brighton, United Kingdom',
    'Plymouth, United Kingdom',
    'Northampton, United Kingdom',
    'Reading, United Kingdom',
    'Luton, United Kingdom',
    'Wolverhampton, United Kingdom',
    'Bolton, United Kingdom',
    'Bournemouth, United Kingdom',
    'Norwich, United Kingdom',
    'Swindon, United Kingdom',
    'Swansea, United Kingdom',
    'Southend-on-Sea, United Kingdom',
    'Middlesbrough, United Kingdom',
    'Peterborough, United Kingdom',
    'Cambridge, United Kingdom',
    'Oxford, United Kingdom',
    'York, United Kingdom',
    'Bath, United Kingdom',
    'Canterbury, United Kingdom',
    
    # Canada
    'Toronto, Canada',
    'Montreal, Canada',
    'Vancouver, Canada',
    'Calgary, Canada',
    'Edmonton, Canada',
    'Ottawa, Canada',
    'Winnipeg, Canada',
    'Quebec City, Canada',
    'Hamilton, Canada',
    'Kitchener, Canada',
    'London, Canada',
    'Victoria, Canada',
    'Halifax, Canada',
    'Oshawa, Canada',
    'Windsor, Canada',
    'Saskatoon, Canada',
    'Regina, Canada',
    'Sherbrooke, Canada',
    'Barrie, Canada',
    'Kelowna, Canada',
    'Abbotsford, Canada',
    'Kingston, Canada',
    'Sudbury, Canada',
    'Saguenay, Canada',
    'Trois-Rivières, Canada',
    'Guelph, Canada',
    'Cambridge, Canada',
    'St. Catharines, Canada',
    'Thunder Bay, Canada',
    'Waterloo, Canada',
    
    # Australia
    'Sydney, Australia',
    'Melbourne, Australia',
    'Brisbane, Australia',
    'Perth, Australia',
    'Adelaide, Australia',
    'Gold Coast, Australia',
    'Canberra, Australia',
    'Newcastle, Australia',
    'Wollongong, Australia',
    'Logan City, Australia',
    'Geelong, Australia',
    'Hobart, Australia',
    'Townsville, Australia',
    'Cairns, Australia',
    'Darwin, Australia',
    'Toowoomba, Australia',
    'Ballarat, Australia',
    'Bendigo, Australia',
    'Albury, Australia',
    'Launceston, Australia',
    'Mackay, Australia',
    'Rockhampton, Australia',
    'Bunbury, Australia',
    'Bundaberg, Australia',
    'Coffs Harbour, Australia',
    'Wagga Wagga, Australia',
    'Hervey Bay, Australia',
    'Mildura, Australia',
    'Shepparton, Australia',
    'Gladstone, Australia',
    
    # Japan
    'Tokyo, Japan',
    'Yokohama, Japan',
    'Osaka, Japan',
    'Nagoya, Japan',
    'Sapporo, Japan',
    'Fukuoka, Japan',
    'Kobe, Japan',
    'Kyoto, Japan',
    'Kawasaki, Japan',
    'Saitama, Japan',
    'Hiroshima, Japan',
    'Sendai, Japan',
    'Chiba, Japan',
    'Kitakyushu, Japan',
    'Sakai, Japan',
    'Niigata, Japan',
    'Hamamatsu, Japan',
    'Okayama, Japan',
    'Sagamihara, Japan',
    'Kumamoto, Japan',
    
    # South Korea
    'Seoul, South Korea',
    'Busan, South Korea',
    'Incheon, South Korea',
    'Daegu, South Korea',
    'Daejeon, South Korea',
    'Gwangju, South Korea',
    'Ulsan, South Korea',
    'Suwon, South Korea',
    'Changwon, South Korea',
    'Seongnam, South Korea',
    'Goyang, South Korea',
    'Yongin, South Korea',
    'Bucheon, South Korea',
    'Ansan, South Korea',
    'Cheongju, South Korea',
    'Jeonju, South Korea',
    'Anyang, South Korea',
    'Cheonan, South Korea',
    'Namyangju, South Korea',
    'Pohang, South Korea',
    
    # China
    'Shanghai, China',
    'Beijing, China',
    'Chongqing, China',
    'Tianjin, China',
    'Guangzhou, China',
    'Shenzhen, China',
    'Wuhan, China',
    'Dongguan, China',
    'Chengdu, China',
    'Nanjing, China',
    'Xi\'an, China',
    'Shenyang, China',
    'Hangzhou, China',
    'Foshan, China',
    'Harbin, China',
    'Qingdao, China',
    'Suzhou, China',
    'Dalian, China',
    'Zhengzhou, China',
    'Shantou, China',
    
    # Southeast Asia
    'Singapore, Singapore',
    'Kuala Lumpur, Malaysia',
    'Johor Bahru, Malaysia',
    'George Town, Malaysia',
    'Ipoh, Malaysia',
    'Shah Alam, Malaysia',
    'Petaling Jaya, Malaysia',
    'Seremban, Malaysia',
    'Kuching, Malaysia',
    'Kota Kinabalu, Malaysia',
    'Bangkok, Thailand',
    'Chiang Mai, Thailand',
    'Pattaya, Thailand',
    'Phuket, Thailand',
    'Hat Yai, Thailand',
    'Nonthaburi, Thailand',
    'Pak Kret, Thailand',
    'Si Racha, Thailand',
    'Chon Buri, Thailand',
    'Rayong, Thailand',
    'Jakarta, Indonesia',
    'Surabaya, Indonesia',
    'Bandung, Indonesia',
    'Bekasi, Indonesia',
    'Medan, Indonesia',
    'Tangerang, Indonesia',
    'Depok, Indonesia',
    'Semarang, Indonesia',
    'Palembang, Indonesia',
    'Makassar, Indonesia',
    'Ho Chi Minh City, Vietnam',
    'Hanoi, Vietnam',
    'Haiphong, Vietnam',
    'Can Tho, Vietnam',
    'Da Nang, Vietnam',
    'Bien Hoa, Vietnam',
    'Hue, Vietnam',
    'Nha Trang, Vietnam',
    'Buon Ma Thuot, Vietnam',
    'Vung Tau, Vietnam',
    
    # India
    'Mumbai, India',
    'Delhi, India',
    'Bangalore, India',
    'Hyderabad, India',
    'Ahmedabad, India',
    'Chennai, India',
    'Kolkata, India',
    'Surat, India',
    'Pune, India',
    'Jaipur, India',
    'Lucknow, India',
    'Kanpur, India',
    'Nagpur, India',
    'Indore, India',
    'Thane, India',
    'Bhopal, India',
    'Visakhapatnam, India',
    'Patna, India',
    'Vadodara, India',
    'Ghaziabad, India',
    
    # Europe
    'Paris, France',
    'Marseille, France',
    'Lyon, France',
    'Toulouse, France',
    'Nice, France',
    'Nantes, France',
    'Strasbourg, France',
    'Montpellier, France',
    'Bordeaux, France',
    'Lille, France',
    'Berlin, Germany',
    'Hamburg, Germany',
    'Munich, Germany',
    'Cologne, Germany',
    'Frankfurt, Germany',
    'Stuttgart, Germany',
    'Düsseldorf, Germany',
    'Dortmund, Germany',
    'Essen, Germany',
    'Leipzig, Germany',
    'Rome, Italy',
    'Milan, Italy',
    'Naples, Italy',
    'Turin, Italy',
    'Palermo, Italy',
    'Genoa, Italy',
    'Bologna, Italy',
    'Florence, Italy',
    'Bari, Italy',
    'Catania, Italy',
    'Madrid, Spain',
    'Barcelona, Spain',
    'Valencia, Spain',
    'Seville, Spain',
    'Zaragoza, Spain',
    'Málaga, Spain',
    'Murcia, Spain',
    'Palma, Spain',
    'Las Palmas, Spain',
    'Bilbao, Spain',
    'Amsterdam, Netherlands',
    'Rotterdam, Netherlands',
    'The Hague, Netherlands',
    'Utrecht, Netherlands',
    'Eindhoven, Netherlands',
    'Tilburg, Netherlands',
    'Groningen, Netherlands',
    'Almere, Netherlands',
    'Breda, Netherlands',
    'Nijmegen, Netherlands',
    'Vienna, Austria',
    'Graz, Austria',
    'Linz, Austria',
    'Salzburg, Austria',
    'Innsbruck, Austria',
    'Klagenfurt, Austria',
    'Villach, Austria',
    'Wels, Austria',
    'Sankt Pölten, Austria',
    'Dornbirn, Austria',
    'Zurich, Switzerland',
    'Geneva, Switzerland',
    'Basel, Switzerland',
    'Lausanne, Switzerland',
    'Bern, Switzerland',
    'Winterthur, Switzerland',
    'Lucerne, Switzerland',
    'St. Gallen, Switzerland',
    'Lugano, Switzerland',
    'Biel/Bienne, Switzerland',
    
    # Latin America
    'São Paulo, Brazil',
    'Rio de Janeiro, Brazil',
    'Brasília, Brazil',
    'Salvador, Brazil',
    'Fortaleza, Brazil',
    'Belo Horizonte, Brazil',
    'Manaus, Brazil',
    'Curitiba, Brazil',
    'Recife, Brazil',
    'Goiânia, Brazil',
    'Buenos Aires, Argentina',
    'Córdoba, Argentina',
    'Rosario, Argentina',
    'Mendoza, Argentina',
    'Tucumán, Argentina',
    'La Plata, Argentina',
    'Mar del Plata, Argentina',
    'Salta, Argentina',
    'Santa Fe, Argentina',
    'San Juan, Argentina',
    'Mexico City, Mexico',
    'Guadalajara, Mexico',
    'Monterrey, Mexico',
    'Puebla, Mexico',
    'Tijuana, Mexico',
    'León, Mexico',
    'Juárez, Mexico',
    'Torreón, Mexico',
    'Querétaro, Mexico',
    'San Luis Potosí, Mexico',
    'Lima, Peru',
    'Arequipa, Peru',
    'Trujillo, Peru',
    'Chiclayo, Peru',
    'Huancayo, Peru',
    'Cusco, Peru',
    'Chimbote, Peru',
    'Piura, Peru',
    'Iquitos, Peru',
    'Tacna, Peru',
    'Bogotá, Colombia',
    'Medellín, Colombia',
    'Cali, Colombia',
    'Barranquilla, Colombia',
    'Cartagena, Colombia',
    'Cúcuta, Colombia',
    'Soledad, Colombia',
    'Ibagué, Colombia',
    'Bucaramanga, Colombia',
    'Soacha, Colombia',
    'Santiago, Chile',
    'Puente Alto, Chile',
    'Antofagasta, Chile',
    'Viña del Mar, Chile',
    'Valparaíso, Chile',
    'Talcahuano, Chile',
    'San Bernardo, Chile',
    'Temuco, Chile',
    'Iquique, Chile',
    'Concepción, Chile',
    
    # Middle East & Africa
    'Dubai, United Arab Emirates',
    'Abu Dhabi, United Arab Emirates',
    'Sharjah, United Arab Emirates',
    'Al Ain, United Arab Emirates',
    'Ajman, United Arab Emirates',
    'Ras Al Khaimah, United Arab Emirates',
    'Fujairah, United Arab Emirates',
    'Umm Al Quwain, United Arab Emirates',
    'Doha, Qatar',
    'Al Rayyan, Qatar',
    'Umm Salal, Qatar',
    'Al Wakrah, Qatar',
    'Al Khor, Qatar',
    'Dukhan, Qatar',
    'Mesaieed, Qatar',
    'Kuwait City, Kuwait',
    'Ahmadi, Kuwait',
    'Hawalli, Kuwait',
    'As Salimiyah, Kuwait',
    'Sabah as Salim, Kuwait',
    'Riyadh, Saudi Arabia',
    'Jeddah, Saudi Arabia',
    'Mecca, Saudi Arabia',
    'Medina, Saudi Arabia',
    'Dammam, Saudi Arabia',
    'Khobar, Saudi Arabia',
    'Tabuk, Saudi Arabia',
    'Buraidah, Saudi Arabia',
    'Khamis Mushait, Saudi Arabia',
    'Hail, Saudi Arabia',
    'Cairo, Egypt',
    'Alexandria, Egypt',
    'Giza, Egypt',
    'Shubra El Kheima, Egypt',
    'Port Said, Egypt',
    'Suez, Egypt',
    'Luxor, Egypt',
    'Al Mahallah al Kubra, Egypt',
    'Mansoura, Egypt',
    'Tanta, Egypt',
    'Cape Town, South Africa',
    'Johannesburg, South Africa',
    'Durban, South Africa',
    'Pretoria, South Africa',
    'Port Elizabeth, South Africa',
    'Pietermaritzburg, South Africa',
    'Benoni, South Africa',
    'Tembisa, South Africa',
    'East London, South Africa',
    'Vereeniging, South Africa',
    'Lagos, Nigeria',
    'Kano, Nigeria',
    'Ibadan, Nigeria',
    'Kaduna, Nigeria',
    'Port Harcourt, Nigeria',
    'Benin City, Nigeria',
    'Maiduguri, Nigeria',
    'Zaria, Nigeria',
    'Aba, Nigeria',
    'Jos, Nigeria',
]

def is_valid_location(location_string):
    #Validates if a location string exists in our predefined list.
    #location_string (str): Location string to validate
    #Returns bool: True if location is valid, False otherwise
    if not location_string or not isinstance(location_string, str):
        return False
    
    normalized_input = location_string.strip()
    
    # Check if it exists in our predefined locations (case-insensitive)
    return any(location.lower() == normalized_input.lower() for location in LOCATIONS_DATA)

def search_locations(query, limit=10):
    #query (str): Search query
    #limit (int): Maximum number of results to return
        
    # Returns list: List of matching locations, up to the specified limit
    if not query or not isinstance(query, str):
        return []
    
    query_lower = query.lower().strip()
    if not query_lower:
        return []
    
    matches = []
    
    # Exact matches first
    for location in LOCATIONS_DATA:
        if location.lower() == query_lower:
            matches.append(location)
    
    # City starts with query
    for location in LOCATIONS_DATA:
        city = location.split(', ')[0].lower()
        if city.startswith(query_lower) and location not in matches:
            matches.append(location)
    
    # City contains query
    for location in LOCATIONS_DATA:
        city = location.split(', ')[0].lower()
        if query_lower in city and location not in matches:
            matches.append(location)
    
    # Full location contains query
    for location in LOCATIONS_DATA:
        if query_lower in location.lower() and location not in matches:
            matches.append(location)
    
    return matches[:limit]

