# Generated by Django 5.2.6 on 2025-10-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Lead Guitarist Needed'", max_length=200)),
                ('band_name', models.CharField(help_text='Name of the band posting this opportunity', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the opportunity and requirements')),
                ('instruments_needed', models.CharField(help_text="Comma-separated list: 'Guitar, Bass, Drums'", max_length=200)),
                ('genres', models.CharField(help_text="Comma-separated list: 'Rock, Alternative, Jazz'", max_length=200)),
                ('location', models.CharField(help_text='City, State or general area', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this listing is currently accepting applications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band_admin', models.ForeignKey(help_text='Band admin who created this listing', limit_choices_to={'role': 'band'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Band Listing',
                'verbose_name_plural': 'Band Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
