# Generated by Django 5.2.6 on 2025-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_add_standardized_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
    ]
