# Generated by Django 4.2.25 on 2025-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the band is based or where performances will take place', max_length=200, null=True),
        ),
    ]
