# Generated by Django 4.2.25 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(default='Sample Location', help_text='Location where the band is based or where performances will take place', max_length=200),
            preserve_default=False,
        ),
    ]
