# Generated by Django 4.2.25 on 2025-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='band_name',
            field=models.CharField(help_text='Name of the band posting this opportunity (max 50 chars)', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Detailed description of the opportunity and requirements (max 500 chars)', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text="e.g., 'Lead Guitarist Needed' (max 80 chars)", max_length=80),
        ),
    ]
