# Generated by Django 4.2.25 on 2025-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_band_name_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_lineup',
            field=models.TextField(blank=True, help_text='Current band members (optional, for transparency)', null=True),
        ),
    ]
