# Generated by Django 4.2.25 on 2025-11-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_genres_user_instruments_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('musician', 'Musician'), ('band', 'Band Admin'), ('admin', 'Administrator')], default='musician', max_length=50),
        ),
    ]
