# Generated by Django 4.2.25 on 2025-12-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_bio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.BooleanField(default=True, help_text='Available for new opportunities'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lineup',
            field=models.TextField(blank=True, help_text='Current band lineup (optional)', null=True),
        ),
    ]
