# Generated by Django 4.2.25 on 2025-12-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_availability_and_lineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_lineup',
        ),
    ]
