# Generated by Django 4.2.25 on 2025-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from band admin to musician', null=True),
        ),
    ]
